#!/bin/bash                                                                                               
# Name: M***V***R***                                                                             
# Date: November 15, 2019                                                                                 
# File: caseitsayes                                                                                       
# Usage: Rewrite itsayes using a case command.                                                            

if [ "$#" -eq 0 ]
then
    echo "No argumen supplied."
    exit 1
fi
    case $1 in
        Y|y|yes|Yes|YES) exit 0 ;;
              *) exit 1 ;;
    esac
