#!/bin/bash                                                                                               
# Name: M***V***R***                                                                             
# Date: November 15, 2019                                                                                 
# File: itsayes                                                                                        
# Week: 4, Conditional Statements                                                                         
# Usage: Returns an exit status of 0 if its argument is "yes",                                            
#        and "1" otherwise.                                                                               

if [ "$#" -eq 0 ]
then
    echo "No argument supplied."
else
    if [ "$1" = 'Y' ] || [ "$1" = 'y' ] || [ "$1" = 'yes' ] || [ "$1" = 'Yes' ] || [ "$1" = 'YES' ] ;
    then
        exit 0
    else
        exit 1
    fi
fi
